chartmuseum:
  env:
    open:
      DISABLE_API: false
      AUTH_ANONYMOUS_GET: true
    secret:
      BASIC_AUTH_USER: admin # Change me!
      BASIC_AUTH_PASS: admin # Change me!
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 80m
      memory: 64Mi
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      cm.192.168.99.109.nip.io: # Change me!
      - /

jenkins:
  Master:
    ImageTag: "2.167-alpine"
    Cpu: "2000m"
    Memory: "500Mi"
    ServiceType: ClusterIP
    ServiceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    GlobalLibraries: true
    InstallPlugins:
    - blueocean:1.13.2
    - command-launcher:1.3
    - credentials:2.1.18
    - durable-task:1.29
    - ec2:1.42
    - git-client:2.7.6
    - git:3.9.3
    - github-oauth:0.31
    - github:1.29.4
    - google-compute-engine:2.0.0
    - jdk-tool:1.2
    - kubernetes:1.14.8
    - pegdown-formatter:1.3
    - pipeline-model-definition:1.3.6
    - pipeline-utility-steps:2.3.0
    - script-security:1.54
    - slack:2.18
    - ssh-agent:1.17
    - ssh-slaves:1.29.4
    - thinBackup:1.9
    - workflow-aggregator:2.5
    - workflow-durable-task-step:2.19
    Ingress:
      Annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        ingress.kubernetes.io/ssl-redirect: "false"
        ingress.kubernetes.io/proxy-body-size: 50m
        ingress.kubernetes.io/proxy-request-buffering: "off"
    HostName: jenkins.192.168.99.109.nip.io # Change me!
    CustomConfigMap: true
    CredentialsXmlSecret: jenkins-credentials
    SecretsFilesSecret: jenkins-secrets
    DockerVM: false
  rbac:
    install: true
go-demo-5:
  ingress:
    host: go-demo-5.192.168.99.109.nip.io
